# Generated by Django 2.2.7 on 2019-11-14 21:47

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_account_lastday'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', users.models.AccountManager()),
            ],
        ),
    ]
