# Generated by Django 2.2.7 on 2019-12-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191114_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password_reset',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
