# Generated by Django 2.2.7 on 2019-12-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('published', models.BooleanField()),
            ],
        ),
    ]
