# Generated by Django 2.2.7 on 2019-12-09 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='ownerid',
            field=models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.PROTECT, to='players.Player'),
        ),
    ]
