from django.db import models

from users.models import Account
# Create your models here.


class Player(models.Model):
    name = models.CharField(max_length=35)
    world_id = models.PositiveIntegerField()
    group_id = models.IntegerField()
    account = models.ForeignKey(Account, models.DO_NOTHING)
    level = models.IntegerField()
    vocation = models.IntegerField()
    health = models.IntegerField()
    healthmax = models.IntegerField()
    experience = models.BigIntegerField()
    lookbody = models.IntegerField()
    lookfeet = models.IntegerField()
    lookhead = models.IntegerField()
    looklegs = models.IntegerField()
    looktype = models.IntegerField()
    lookaddons = models.IntegerField()
    maglevel = models.IntegerField()
    mana = models.IntegerField()
    manamax = models.IntegerField()
    manaspent = models.IntegerField()
    soul = models.PositiveIntegerField()
    town_id = models.IntegerField()
    posx = models.IntegerField()
    posy = models.IntegerField()
    posz = models.IntegerField()
    conditions = models.TextField()
    cap = models.IntegerField()
    sex = models.IntegerField()
    lastlogin = models.BigIntegerField()
    lastip = models.PositiveIntegerField()
    save = models.IntegerField()
    skull = models.PositiveIntegerField()
    skulltime = models.IntegerField()
    rank_id = models.IntegerField()
    guildnick = models.CharField(max_length=255)
    lastlogout = models.BigIntegerField()
    blessings = models.IntegerField()
    balance = models.BigIntegerField()
    stamina = models.BigIntegerField()
    direction = models.IntegerField()
    loss_experience = models.IntegerField()
    loss_mana = models.IntegerField()
    loss_skills = models.IntegerField()
    loss_containers = models.IntegerField()
    loss_items = models.IntegerField()
    premend = models.IntegerField()
    online = models.IntegerField()
    marriage = models.PositiveIntegerField()
    promotion = models.IntegerField()
    deleted = models.IntegerField()
    description = models.CharField(max_length=77)
    created = models.IntegerField()
    hidden = models.IntegerField()
    comment = models.TextField()
    exphist_lastexp = models.BigIntegerField()
    exphist1 = models.BigIntegerField()
    exphist2 = models.BigIntegerField()
    exphist3 = models.BigIntegerField()
    exphist4 = models.BigIntegerField()
    exphist5 = models.BigIntegerField()
    exphist6 = models.BigIntegerField()
    exphist7 = models.BigIntegerField()
    onlinetimetoday = models.BigIntegerField()
    onlinetime1 = models.BigIntegerField()
    onlinetime2 = models.BigIntegerField()
    onlinetime3 = models.BigIntegerField()
    onlinetime4 = models.BigIntegerField()
    onlinetime5 = models.BigIntegerField()
    onlinetime6 = models.BigIntegerField()
    onlinetime7 = models.BigIntegerField()
    onlinetimeall = models.BigIntegerField()

    class Meta:
        managed = True
        db_table = 'players'
        unique_together = (('name', 'deleted'),)
