# Generated by Django 2.2.7 on 2019-11-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='save',
            new_name='save_character',
        ),
        migrations.AlterField(
            model_name='player',
            name='save_character',
            field=models.IntegerField(db_column='save'),
        ),
    ]
