# Generated by Django 2.2.7 on 2019-12-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20191201_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='experience',
            field=models.BigIntegerField(default=4200),
        ),
    ]
